# fly.toml app configuration file generated for pptr on 2024-02-26T22:41:22+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pptr-hospital'
primary_region = 'nrt'

[build]


  
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  
